### ISSUE TITLE
WebfluxRateLimitTest not passing

### ISSUE THREAD

**Issue by sbilello** [MarcGiffing/bucket4j-spring-boot-starter-examples#3]
@MarcGiffing 
I was trying to use your dependencies and replicate the test cases. 
I see that it does not pass even in this example repository.
```
java.lang.AssertionError: Response header 'X-Rate-Limit-Remaining' expected:<[9]> but was:<null>

> GET /world
> WebTestClient-Request-Id: [1]

No content

< 200 OK
< Content-Type: [text/plain;charset=UTF-8]
< Content-Length: [14]

Content not available yet


	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:197)
	at org.springframework.test.web.reactive.server.HeaderAssertions.assertHeader(HeaderAssertions.java:176)
	at org.springframework.test.web.reactive.server.HeaderAssertions.valueEquals(HeaderAssertions.java:56)
	at com.giffing.bucket4j.spring.boot.starter.examples.webflux.WebfluxRateLimitTest.successfulWebRequest(WebfluxRateLimitTest.java:73)
```

**Comment by MarcGiffing** [comment]
Does it work now?
